### ISSUE TITLE
to_rawz appends to new buf in wrong place

### ISSUE THREAD

**Issue by lnyng** [framelabs-eu/tools#1]
https://github.com/framelabs-eu/tools/blob/a350f012d16437ce40fc7babbf23a6fff28b3f48/to_rawz.py#L31

It appends to the output buf every odd pixel (`i == 0`). As a result, it will skip the second pixel, push all other pixels to its right by one (right-most pixels on each row becomes first pixel on next row), and causes the last pixel to be omitted (last `value` is not appended). It should append to buf only when `i == 1`.

**Comment by clashman** [comment]
Thanks for pointing out the off-by-one-error. Fixed.
