### ISSUE TITLE
from_raw flips every pixel pairs by mistake

### ISSUE THREAD

**Issue by lnyng** [framelabs-eu/tools#2]
https://github.com/framelabs-eu/tools/blob/a350f012d16437ce40fc7babbf23a6fff28b3f48/from_rawz.py#L30-L31

Since index goes from left to right, `buf[idx//w][idx%w]` should be on the left to `buf[(idx+1)//w][(idx+1)%w]`. Therefore, they should be assigned to `first, sec` respectively instead of `sec, first`.

Interestingly, when combined with https://github.com/framelabs-eu/tools/issues/1, the outcome is less wrong because https://github.com/framelabs-eu/tools/issues/1 also effectively flips every pixel pairs.

**Comment by clashman** [comment]
This is not a bug. The lower four bits of the binary format correspond to the left pixel of a pixel pair, the higher four bits to the right pixel.

**Comment by lnyng** [comment]
According to the support page: https://framelabs.eu/wp-content/uploads/docs/ArtFrame%20Kit%20%E2%80%93%20Manual.html#image-format-rawz
> Every byte contains two pixels, with the left pixel as the more significant bits.

Since you have changed the implementation in to_rawz.py to have the lower four bits as the left pixel, the implementation is now consistent. But it will be nice to document it somewhere in this repo.

BTW it's a bit confusing to use `not i % 2` to say "i is an even number": https://github.com/framelabs-eu/tools/blob/master/to_rawz.py#L26. `i % 2 == 0` is probably a better option.

**Comment by clashman** [comment]
> Since you have changed the implementation in to_rawz.py to have the lower four bits as the left pixel, the implementation is now consistent. But it will be nice to document it somewhere in this repo.

Actually, the left pixel always has been the lower four bits. The ArtFrame devices have always interpreted the bits like that. It was just documented in the opposite way, which most probably happened because I was tricked by #1 when I read the code in the process of documenting it 😅


> BTW it's a bit confusing to use not i % 2 to say "i is an even number": https://github.com/framelabs-eu/tools/blob/master/to_rawz.py#L26. i % 2 == 0 is probably a better option.

I had the same train of thought but was too lazy to change it. Done now.
